### ISSUE TITLE
cannot connect to X server

### ISSUE THREAD

**Issue by Dreamdancer100** [johanymerson/7096#1]
I have installed all necessary programs and addons but when I want to run the script this message comes up. I restarted X Server. my script is in /opt/iobroker/tunze/tunze_control.py do you need a display to run the program? what can i do to fix this issue.

**Comment by johanymerson** [comment]
Yes, the 7096.py script is a simple graphical tool to configure the Tunze 7096 controller. It is not intended to run from a script or headless.
The script could for sure be modified to use hard-coded values or values from a command line to configure the controller instead.
What are you trying to do with the controller? I get a feeling that you try to control the pumps runtime. Unfortunately I don't think that will be possible. From what I know only the configuration of the controller can be changed over USB.

**Comment by Dreamdancer100** [comment]
I control my entire seawater tank using iobroker and hardware that I built myself. With sensors floats and so on. The main system in a raspberry pi 4 where Linux is installed and also Python. Since I only have a netbook running for the tunze controller to change the program manually now and then I would like the control programs that I have created and saved via the tunze controller software that I can use the ioBroker javascript adapter with can send blockly to the multicontroller via exec command in order to change the programs in a time-controlled manner. furthermore i connected the pumps to 240 volt switching relays and they should be switched off during the aquarium food break but why are they still on? but if I can send the feed break it would be great. then I installed an illuminance sensor under my lamps and I have a control system that detects when the lamps generate flashes sporadically, then I would like to send the program to the multicontroller with the wave mode switched on. I hope you really really can help me because I search over one year for an script controlling the multicontroller over Linux without any Windows Computer that is really important for me that I can run this constellation

**Comment by Dreamdancer100** [comment]
I'm sorry that I'm only now writing, I had a lot to do at work and also problems in my family! It would be great if you could help me to control my tunze pumps with the multicontroller directly connected to the raspi via usb and Control with blockly ore JavaScript ore over your control script implemented into blockly
