### ISSUE TITLE
X-Server not online

### ISSUE THREAD

**Issue by Dreamdancer100** [johanymerson/7096#2]
I need help! 
I would like to control my multicontroller via my Raspberry Pi via iobroker and Blockly. but when I call the script via ssh I get the message that the X server is not accessible. What do I have to set on the script and do not have to specify the USB port via which the controller is connected

**Comment by johanymerson** [comment]
Hi,

Please read my response to your previous question on this subject:
https://github.com/johanymerson/7096/issues/1

What you want to do is not possible. This little script is graphical and needs a display and user interaction. Apart from that, the controller can only be configured, not controlled, over USB. If you were to send a new configuration every time you want a pump to change speed, you would likely wear out the controller EEPROM in no time at all.

If you want to control the pumps directly, I would suggest using PWM outputs from an Arduino to do so.

**Comment by Dreamdancer100** [comment]
Ok! Thanks for answer.
I test it with Blockly and pwm control but script in blockly ore JavaScript is to extrem that ioBroker software crashes when I want to control the pumps directly. 
it is a pity that your script is not usable for my application. isn't it somehow possible to send certain programs to the multi controller with a command in linux? That I can control multi controller with Blockly
